version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 525158249545.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t uniqin-test:latest .
      - docker tag uniqin-test:latest 525158249545.dkr.ecr.us-west-2.amazonaws.com/prometheus-sample:latest
      - docker tag uniqin-test:latest 525158249545.dkr.ecr.us-west-2.amazonaws.com/prometheus-sample:v$CODEBUILD_BUILD_NUMBER      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 525158249545.dkr.ecr.us-west-2.amazonaws.com/prometheus-sample:latest
      - docker push 525158249545.dkr.ecr.us-west-2.amazonaws.com/prometheus-sample:v$CODEBUILD_BUILD_NUMBER
      - export AWS_DEFAULT_REGION=us-west-2
      - aws eks update-kubeconfig --name main
      - aws sts get-caller-identity
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - ./kubectl version
      - sed "s/CODEBUILD_BUILD_NUMBER/$CODEBUILD_BUILD_NUMBER/g" kube-deployment.yaml > kube.yaml
      - cat kube.yaml
      - ./kubectl apply -f kube.yaml

