apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-sample

---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sample
  namespace: prometheus-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-sample
  template:
    metadata:
      labels:
        app: prometheus-sample
    spec:
      containers:
      - name: prometheus-sample
        image: 525158249545.dkr.ecr.us-west-2.amazonaws.com/prometheus-sample:latest

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-sample
  namespace: prometheus-sample
spec:
  selector:
    app: prometheus-sample
  ports:
  - name: http
    port: 8080
    targetPort: 8080
