apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-sample

---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-memory-queue
  namespace: prometheus-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-memory-queue
  template:
    metadata:
      labels:
        app: in-memory-queue
    spec:
      containers:
      - name: in-memory-queue
        image: 525158249545.dkr.ecr.us-west-2.amazonaws.com/prometheus-sample:vCODEBUILD_BUILD_NUMBER

---

apiVersion: v1
kind: Service
metadata:
  name: in-memory-queue
  namespace: prometheus-sample
spec:
  selector:
    app: in-memory-queue
  ports:
  - name: http
    port: 8080
    targetPort: 8080
